[package]
name = "voxel-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
noise = "0.9.0"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.64"                  # JSの型（ArrayBufferなど）を扱うため

[profile.release]
lto = true
opt-level = 'z'
